[platformio]
src_dir = .

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial monitor configuration
monitor_speed = 115200

; Build flags
build_flags = 
    -std=gnu++11
    -DCORE_DEBUG_LEVEL=3

; Library dependencies
lib_deps = 
    https://github.com/AploCoin/AploEmbed.git
    ; Add other dependencies here if needed

; Source directory is configured in the [platformio] section above.
