[platformio]
src_dir = .

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    https://github.com/AploCoin/AploEmbed.git#master

build_flags =
    -DCORE_DEBUG_LEVEL=3
